version: '3.5'

services:
  signaler:
    build:
      context: ./

    networks:
      - nginx-proxy
    restart: always

    environment:
      VIRTUAL_HOST: "signaler.getid.org"
      LETSENCRYPT_HOST: "signaler.getid.org"

networks:
  nginx-proxy:
    external: true
